import type { WeeklyReport } from '../types'

function drawWrappedText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const words = text.split(' ')
  let line = ''
  let cy = y
  for (const word of words) {
    const test = line ? `${line} ${word}` : word
    if (ctx.measureText(test).width > maxWidth && line) {
      ctx.fillText(line, x, cy)
      line = word
      cy += lineHeight
    } else {
      line = test
    }
  }
  if (line) {
    ctx.fillText(line, x, cy)
    cy += lineHeight
  }
  return cy
}

export async function renderWeeklyReportToBlob(
  childName: string,
  report: WeeklyReport,
): Promise<Blob | null> {
  const canvas = document.createElement('canvas')
  canvas.width = 720
  canvas.height = 900
  const ctx = canvas.getContext('2d')
  if (!ctx) return null

  ctx.fillStyle = '#f4f6fb'
  ctx.fillRect(0, 0, canvas.width, canvas.height)

  ctx.fillStyle = '#4f46e5'
  ctx.fillRect(0, 0, canvas.width, 120)

  ctx.fillStyle = '#ffffff'
  ctx.font = 'bold 28px system-ui, sans-serif'
  ctx.fillText('Little Dream', 40, 52)
  ctx.font = '22px system-ui, sans-serif'
  ctx.fillText(`${childName} · ${report.periodLabel}`, 40, 88)

  let y = 160
  ctx.fillStyle = '#0f172a'
  ctx.font = 'bold 20px system-ui, sans-serif'
  ctx.fillText('Weekly sleep summary', 40, y)
  y += 40

  ctx.font = '18px system-ui, sans-serif'
  ctx.fillText(`Average sleep: ${report.avgTotalHours}h / day`, 40, y)
  y += 32
  ctx.fillText(`Average naps: ${report.avgNapCount} / day`, 40, y)
  y += 32
  if (report.avgBedtime) {
    ctx.fillText(`Typical bedtime: ${report.avgBedtime}`, 40, y)
    y += 32
  }

  y += 16
  ctx.font = '16px system-ui, sans-serif'
  ctx.fillStyle = '#475569'
  for (const h of report.highlights) {
    y = drawWrappedText(ctx, `• ${h}`, 40, y, 640, 26) + 8
  }

  ctx.fillStyle = '#94a3b8'
  ctx.font = '13px system-ui, sans-serif'
  ctx.fillText('Generated by Little Dream', 40, 860)

  return new Promise((resolve) => {
    canvas.toBlob((blob) => resolve(blob), 'image/png', 0.92)
  })
}

export async function shareWeeklyReportImage(
  childName: string,
  report: WeeklyReport,
): Promise<'shared' | 'downloaded' | 'failed'> {
  const blob = await renderWeeklyReportToBlob(childName, report)
  if (!blob) return 'failed'

  const file = new File([blob], `little-dream-weekly-${childName.replace(/\s+/g, '-')}.png`, {
    type: 'image/png',
  })

  if (navigator.share && navigator.canShare?.({ files: [file] })) {
    try {
      await navigator.share({
        title: `${childName} — weekly sleep`,
        files: [file],
      })
      return 'shared'
    } catch {
      /* fall through */
    }
  }

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = file.name
  a.click()
  URL.revokeObjectURL(url)
  return 'downloaded'
}
